Implement image upload via frontend.
oveleon/contao-recommendation-bundle pull request #21
Opened 2023-11-22 23:19 UTC by cliffparnitzky

This PR offers image upload from frontend.

In the settings the upload folder has to be configured.

In the modul configuration for the form, image upload can be actived.

2023-11-23 09:55 UTC, zoglo requested changes

2023-11-23 09:55 UTC, zoglo commented on contao/modules/ModuleRecommendationForm.php
> +            if (!empty($_SESSION['FILES']['image']))
Unsure if this would work in Contao 5:

See: https://github.com/contao/contao/blob/5.x/UPGRADE.md#_session-access-no-longer-mapped-to-symfony-session

2023-11-23 09:55 UTC, zoglo commented on contao/modules/ModuleRecommendationForm.php
> +                'eval'      => ['mandatory' => true, 'extensions' => $this->recommendation_image_extensions, 'storeFile' => true, 'doNotOverwrite' => true, 'uploadFolder' => Config::get('recommendati
Shouldn't we use the valid image extensions that Contao offers?
> Config::get('validImageTypes')

2023-11-23 09:55 UTC, zoglo commented on contao/languages/de/tl_module.xlf
> +        <target>Eine kommagetrennte Liste gültiger Bild-Dateiendungen..</target>
Seems to be a typo here :)

2023-11-23 22:07 UTC, cliffparnitzky commented on contao/modules/ModuleRecommendationForm.php
> +                'eval'      => ['mandatory' => true, 'extensions' => $this->recommendation_image_extensions, 'storeFile' => true, 'doNotOverwrite' => true, 'uploadFolder' => Config::get('recommendati
Yes, less is more.

2023-11-23 22:08 UTC, cliffparnitzky commented on contao/languages/de/tl_module.xlf
> +        <target>Eine kommagetrennte Liste gültiger Bild-Dateiendungen..</target>
Due to using Contao valid image types, this will be removed.

2023-11-23 22:21 UTC, cliffparnitzky commented on contao/modules/ModuleRecommendationForm.php
> +                'eval'      => ['mandatory' => true, 'extensions' => $this->recommendation_image_extensions, 'storeFile' => true, 'doNotOverwrite' => true, 'uploadFolder' => Config::get('recommendati
Removed all unnecessary configuration (simply check in form module, if you want the image upload)

2023-11-23 22:57 UTC, cliffparnitzky commented on contao/modules/ModuleRecommendationForm.php
> +            if (!empty($_SESSION['FILES']['image']))
Currently in Contao 4.13 `$_FILES` is empty and my first test with `$request->getSession()->get('FILES');` is `null`.

Need more tests and ideas.

2023-11-24 16:25 UTC, zoglo commented on contao/modules/ModuleRecommendationForm.php
> +            if (!empty($_SESSION['FILES']['image']))
What about getting the request when the form has been sent. This might be a viable approach.
```php
$request->files->get('myImage')
```

- https://symfony.com/doc/current/controller/upload_file.html
- https://zetcode.com/symfony/uploadfile/

2023-11-28 22:31 UTC, cliffparnitzky commented on contao/modules/ModuleRecommendationForm.php
> +            if (!empty($_SESSION['FILES']['image']))
I have currently no idea, how this works in Contao 5. `$request->files->get('image')` delivers the uploaded file. But this value is a Symphony `UploadedFile`, which has no information about the destination file in the Contao Dbafs.

2024-05-31 18:46 UTC, zoglo commented
Since the bundle structure has changed and the upload needs a rewrite to the symfony upload service, I'll close this stale PR.

Feel free to reopen it when rewriting it using Symfony to make sure it doesn't include legacy code:
https://symfony.com/doc/current/controller/upload_file.html

2024-05-31 18:46 UTC, closed without merging